apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cluster-net
  namespace: {{.Values.namespace}}
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              cluster-net: "true"
  podSelector:
    matchLabels:
      cluster-net: "true"
