apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    service: {{.Values.restName}}
  name: {{.Values.restName}}
  namespace: {{.Values.namespace}}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: {{.Values.host}}
      http:
        paths:
          - backend:
              service:
                name: {{.Values.restName}}
                port:
                  number: {{.Values.crudServicePort}}
            path: /
            pathType: Prefix
