apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{.Values.dbmsName}}
  name: {{.Values.dbmsName}}
  namespace: {{.Values.namespace}}
spec:
  ports:
    - name: "5435"
      port: 5435
      targetPort: 5432
  selector:
    service: {{.Values.dbmsName}}
  type: NodePort
