apiVersion: v1
kind: Service
metadata:
  labels:
    service: crud-service
  name: crud-service
  namespace: {{.Values.namespace}}
spec:
  ports:
    - name: "8080"
      port: {{.Values.crudServicePort}}
      targetPort: {{.Values.crudServicePort}}
  selector:
    service: crud-service
  type: NodePort
