apiVersion: v1
kind: ConfigMap
metadata:
  name: crud-service-config
data:
  SERVER_PORT: "{{.Values.crudServicePort}}"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{.Values.dbmsName}}:{{.Values.ingressDbPort}}/postgres"
  SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: public