apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{.Values.dbmsName}}
  name: {{.Values.dbmsName}}
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: {{.Values.dbmsName}}
  strategy: {}
  template:
    metadata:
      labels:
        cluster-net: "true"
        service: {{.Values.dbmsName}}
    spec:
      containers:
        - env:
            - name: PGDATA
              value: /var/lib/postgresql/data
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: postgres:14.4
          name: {{.Values.dbmsName}}
          ports:
            - containerPort: 5432
          resources: {}
      restartPolicy: Always
